# Generated by Django 3.0.6 on 2020-06-18 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tlessons',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trozporyadok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(max_length=200)),
                ('podiya', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tweek',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Trozklad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nlesson', models.IntegerField()),
                ('idlessons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rozklad.Tlessons')),
                ('idweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rozklad.Tweek')),
            ],
        ),
    ]
