# Generated by Django 3.0.6 on 2020-06-20 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozklad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urtimes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(max_length=200)),
                ('time_end', models.TimeField(max_length=200)),
            ],
        ),
    ]
