# Generated by Django 3.0.6 on 2020-06-22 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rozklad', '0003_auto_20200622_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trozporyadok',
            name='time',
        ),
    ]
