# Generated by Django 3.0.6 on 2020-06-22 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozklad', '0005_auto_20200622_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trozporyadok',
            name='time_start',
            field=models.TimeField(default=datetime.time(0, 0), max_length=200),
        ),
    ]
