# Generated by Django 3.0.6 on 2020-06-22 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rozklad', '0006_auto_20200622_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trozporyadok',
            name='time_end',
            field=models.TimeField(default=datetime.time(0, 0), max_length=200),
        ),
    ]
