# Generated by Django 2.2.20 on 2021-05-04 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rozklad', '0009_auto_20210503_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='other_group_rozklad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idlessons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rozklad.Tlessons')),
                ('idweek', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rozklad.Tweek')),
                ('nomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rozklad.Urtimes')),
            ],
        ),
    ]
